### ISSUE TITLE
symsorter does not create valid `unified` structure

### ISSUE THREAD

**Issue by kristjanvalur** [getsentry/symbolicator#415]
### Environment
I am using a symsorter from the last revision of this repo to create a symbol server image to upload to S3.
However, the output structure is unexpected.

### Steps to Reproduce

1. sort Win64 symbols using `symsorter.exe --output d:\scratch\output2 --prefix Win64 --bundle-id 123 --ignore-errors -z  e:\git\UEPaxDei\Engine\Binaries\Win64`
2. s3 sync to s3 bucket
3. create crash and try to find symbol

### Expected Result
When I create the crash, Sentry will tell me that it cannot fynd my symbol at 
`s3://mybucket/5e/3aa57163c94b9a89e0e1d0b2ab6c081/debuginfo`
This is no wonder, because the file was saved, by symsorter, as
`D:\scratch\output2\Win64\5e\3aa571-63c9-4b9a-89e0-e1d0b2ab6c08\debuginfo`

- Note the hyphens
- Note the missing `1` at the end of the ID string.

This makes the generated tree from symsorter unusable as a source symbol store for sentry.

**Comment by kristjanvalur** [comment]
I've read a lot of rust code today.  I found that the filename is created using DebugId::guid().  Found the debugid as an external resource via the `symbolic` repo.
The missing "1" appears to be the __appendix__, that sentry expects to be 1.  This is apparently not generated.
Also, DebugId doesn't have a method to format things properly.  I think symbolicator needs to do it by removing the hyphens and adding the appendix.  Need to learn some rust to make it work....

**Comment by jan-auer** [comment]
Thank you, this regressed in https://github.com/getsentry/symbolicator/pull/403. We're working on a fix.

**Comment by kristjanvalur** [comment]
Ah, see #424

**Comment by kristjanvalur** [comment]
Hm, now I can't bulid.  I'm sure im doing something wrong, but
```
crate update
crate build --release
```
gives me 
```
 Compiling simple_asn1 v0.4.1
error[E0425]: cannot find function `kill` in crate `libc`
   --> C:\Users\kristjan\.cargo\registry\src\github.com-1ecc6299db9ec823\procspawn-0.9.0\src\proc.rs:332:27
    |
332 |                     libc::kill(pid as i32, libc::SIGKILL);
    |                           ^^^^ not found in `libc`

error[E0425]: cannot find value `SIGKILL` in crate `libc`
   --> C:\Users\kristjan\.cargo\registry\src\github.com-1ecc6299db9ec823\procspawn-0.9.0\src\proc.rs:332:50
    |
332 |                     libc::kill(pid as i32, libc::SIGKILL);
    |                                                  ^^^^^^^ help: a constant with a similar name exists: `SIGILL`
    |
   ::: C:\Users\kristjan\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.94\src\windows\mod.rs:230:1
    |
230 | pub const SIGILL: ::c_int = 4;
    | ------------------------------ similarly named constant `SIGILL` defined here

```

**Comment by kristjanvalur** [comment]
Okay, I'm probably doing something wrong, but I cannot build:
```
cargo clean
cargo build --release
```
gives me
```
 Compiling apple-crash-report-parser v0.4.2
error[E0425]: cannot find function `kill` in crate `libc`
   --> C:\Users\kristjan\.cargo\registry\src\github.com-1ecc6299db9ec823\procspawn-0.9.0\src\proc.rs:332:27
    |
332 |                     libc::kill(pid as i32, libc::SIGKILL);
    |                           ^^^^ not found in `libc`

error[E0425]: cannot find value `SIGKILL` in crate `libc`
   --> C:\Users\kristjan\.cargo\registry\src\github.com-1ecc6299db9ec823\procspawn-0.9.0\src\proc.rs:332:50
    |
332 |                     libc::kill(pid as i32, libc::SIGKILL);
    |                                                  ^^^^^^^ help: a constant with a similar name exists: `SIGILL`
    |
   ::: C:\Users\kristjan\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.80\src\windows\mod.rs:230:1
    |
230 | pub const SIGILL: ::c_int = 4;
    | ------------------------------ similarly named constant `SIGILL` defined here

error: aborting due to 2 previous errors
```

**Comment by kristjanvalur** [comment]
Tried deleting my entire .cargo/git and .cargo/registry folders, still no luck...
I don't get it, Armin's procspawn is calling libc::kill, but this is undefined in the windows version of libc.  How was I able to compile this yesterday?

**Comment by jan-auer** [comment]
Interesting, `SIGKILL` is indeed not defined in the windows version of `libc`:
https://docs.rs/libc/0.2.94/x86_64-pc-windows-msvc/libc/index.html?search=SIGKILL

Did you actually try to build symbolicator, or just `symsorter` in the subfolder? You should be able to build symsorter without procspawn.

**Comment by kristjanvalur** [comment]
That was a good tip.  I was in /symbolicator/symsorter, whereas now it
appears to have moved into symbolicator/crates/symsorter.
I didn't realize that it moved between the two versions and clearly it was
then building the entire sybolicator.  Cheers!

fös., 30. apr. 2021 kl. 18:32 skrifaði Jan Michael Auer <
***@***.***>:
